net.db.url=jdbc:mysql://140.84.173.14:3306/profesionalPractice
net.db.user=spp_app_user
net.db.password=User@2026

ssh.db.url=jdbc:mysql://localhost:3307/profesionalPractice
ssh.db.user=spp_app_user
ssh.db.password=User@2026