net.db.url=jdbc:mysql://140.84.173.14:3306/profesionalPractice
net.db.user=spp_app_user
net.db.password=User@2026
ssh.db.url=jdbc:mysql://localhost:3307/profesionalPractice
ssh.db.user=spp_app_user
ssh.db.password=User@2026
test.db.url=jdbc:h2:mem:testdb;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:schema.sql'\\;RUNSCRIPT FROM 'classpath:data.sql';DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE
test.db.user=sa
test.db.password=