net.db.url=jdbc:mysql://spp-mysql-db-do-user-37371902-0.i.db.ondigitalocean.com:25060/professional-practices-system?sslMode=REQUIRED
net.db.user=spp_app_user
net.db.password=User@2026

ssh.db.url=jdbc:mysql://localhost:3307/profesionalPractice
ssh.db.user=spp_app_user
ssh.db.password=User@2026

test.db.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
test.db.user=sa
test.db.password=

local.db.url=jdbc:mysql://localhost:3306/professional-practices-system
local.db.user=spp_app_user
local.db.password=User@2026