INSERT INTO USUARIO (ID_USUARIO, PASSWORD, NOMBRE, APELLIDOS, ESTADO, GENERO) 
VALUES (1, 'hash_password_segura', 'Josep', 'Prueba', 'Activo', 'Masculino');

INSERT INTO PRACTICANTE (ID_PRACTICANTE, LENGUA_INDIGENA, CALIFICACION) 
VALUES (1, 'Ninguna', 9.5);

INSERT INTO ORGANIZACION_VINCULADA (ID_ORGANIZACION, NOMBRE_ORGANIZACION, ESTADO, CORREO) 
VALUES (1, 'UV Soft', 'Veracruz', 'contacto@uv.mx');

INSERT INTO ACCESS_TOKEN (TOKEN_VALUE, ID_USUARIO) VALUES (123456, 1);