package mx.uv.fei.domain.statemachine.enums;

public enum AppSection {
    SPLASH_SCREEN,
    ADMIN_REGISTRATION,
    LOGIN,
    DASHBOARD,
    PASSWORD_RESET,
    TOKEN_VERIFICATION,
    REGISTER_PRACTITIONER,
    REGISTER_PROFESSOR,
    REGISTER_PROJECT,
    REGISTER_ACTIVITY,
    REGISTER_COORDINATOR
}