package mx.uv.fei.domain.statemachine.enums;

public enum AppSection {
    SPLASH_SCREEN,
    ADMIN_REGISTRATION,
    LOGIN,
    DASHBOARD,
    PASSWORD_RESET,
    TOKEN_VERIFICATION,
    REGISTER_PRACTITIONER,
    REGISTER_PROFESSOR,
    REGISTER_PROJECT,
    REGISTER_ACTIVITY,
    REGISTER_MANAGER,
    REGISTER_COORDINATOR,
    COORDINATOR_DETAILS,
    COORDINATOR_PRACTITIONER_MENU,
    PRIORITIZE_PROJECTS,
    VIEW_PRACTITIONER_PRIORITIES,
    PENDING_PRACTITIONER_SELECTION,
    ASSIGN_PROJECT,
    PROFESSOR_MANAGEMENT_MENU,
    PROJECT_MANAGEMENT_MENU,
    MANAGER_MANAGEMENT_MENU,
    REGISTER_ORGANIZATION,
    ORGANIZATION_MANAGEMENT_MENU
}